import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/Language";
import ModalContainer from "@/components/ModalContainer";
import CookieConsent from "@/components/CookieConsent";
import { ModalProvider } from "@/contexts/Modal";
import { cookies } from "next/headers";
import Menu from "@/components/Menu/Menu";
import Footer from "@/components/Footer";
import { assertAvailibleLanguage } from "@/types/language";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const consentCookie = cookieStore.get("consent")
  const languageCookie = cookieStore.get("language")

  const consent = consentCookie?.value === "true"
  const language = languageCookie === undefined ? "en" : languageCookie.value

  assertAvailibleLanguage(language)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen grid grid-rows-[3rem_1fr_3rem] bg-slate-950/90 text-sky-200`}
      >
        <LanguageProvider consent={consent} cookieLanguage={language}>
          <Menu />
          <ModalProvider>
            <ModalContainer />
            <main className="flex flex-col h-full overflow-auto">
              {children}
            </main>
          </ModalProvider>
          <Footer />
          <CookieConsent />
        </LanguageProvider>
      </body>
    </html>
  );
}

