import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/Language";
import ModalContainer from "@/components/ModalContainer";
import CookieConsent from "@/components/CookieConsent";
import { ModalProvider } from "@/contexts/Modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <CookieConsent />
          <ModalProvider>
            <ModalContainer />
            {children}
          </ModalProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
